apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-web-app-deployment
  namespace: kubernetes-cluster-gouravkansal
  labels:
    app: dotnet-web-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: dotnet-web-app
  template:
    metadata:
      labels:
        app: dotnet-web-app
    spec:
      containers:
        - name: dotnet-web-app
          image: 3153712/gouravkansal_webapp:latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-web-app-develop
  namespace: kubernetes-cluster-gouravkansal
spec:
  type: NodePort
  selector:
    app: dotnet-web-app-develop
  ports:
    - protocol: TCP
      nodePort: 30158
      port: 80
      targetPort: 80
